In [1]:
from dask import array as da 

In [9]:
shp = (100, 100, 100) 
# Fully explicit sizes of all blocks along all dimensions, like 
# ((1000, 1000, 500), (400, 400), (5, 5, 5, 5, 5))
chunks = ((10, 70, 20), 
          (75, 25), 
          (25, 25, 50))

z = da.ones(shp, chunks=chunks)


In [10]:
z

dask.array<ones_like, shape=(100, 100, 100), dtype=float64, chunksize=(70, 75, 50), chunktype=numpy.ndarray>

In [5]:
z.chunks

((10, 50, 40), (50, 50), (25, 25, 25, 25))

In [6]:
z.chunksize

(50, 50, 25)

In [11]:
import numpy as np 

In [46]:
b1 = (np.random.random((3,))*100).astype(int)
b2 = (np.random.random((4,))*100).astype(int)
b3 = (np.random.random((5,))*100).astype(int)

c,d,e = np.meshgrid(b1, b2, b3)
c.shape

(4, 3, 5)

In [47]:
b1

array([85,  7,  7])

In [48]:
b2

array([41, 11, 12, 62])

In [49]:
b3

array([19,  4, 73, 71, 40])

In [52]:
e

array([[[19,  4, 73, 71, 40],
        [19,  4, 73, 71, 40],
        [19,  4, 73, 71, 40]],

       [[19,  4, 73, 71, 40],
        [19,  4, 73, 71, 40],
        [19,  4, 73, 71, 40]],

       [[19,  4, 73, 71, 40],
        [19,  4, 73, 71, 40],
        [19,  4, 73, 71, 40]],

       [[19,  4, 73, 71, 40],
        [19,  4, 73, 71, 40],
        [19,  4, 73, 71, 40]]])

In [43]:
np.argsort(c)

array([[[ 0, 17, 16, ...,  1, 18, 19],
        [ 0, 17, 16, ...,  1, 18, 19],
        [ 0, 17, 16, ...,  1, 18, 19],
        ...,
        [ 0, 17, 16, ...,  1, 18, 19],
        [ 0, 17, 16, ...,  1, 18, 19],
        [ 0, 17, 16, ...,  1, 18, 19]],

       [[ 0, 17, 16, ...,  1, 18, 19],
        [ 0, 17, 16, ...,  1, 18, 19],
        [ 0, 17, 16, ...,  1, 18, 19],
        ...,
        [ 0, 17, 16, ...,  1, 18, 19],
        [ 0, 17, 16, ...,  1, 18, 19],
        [ 0, 17, 16, ...,  1, 18, 19]],

       [[ 0, 17, 16, ...,  1, 18, 19],
        [ 0, 17, 16, ...,  1, 18, 19],
        [ 0, 17, 16, ...,  1, 18, 19],
        ...,
        [ 0, 17, 16, ...,  1, 18, 19],
        [ 0, 17, 16, ...,  1, 18, 19],
        [ 0, 17, 16, ...,  1, 18, 19]],

       ...,

       [[ 0, 17, 16, ...,  1, 18, 19],
        [ 0, 17, 16, ...,  1, 18, 19],
        [ 0, 17, 16, ...,  1, 18, 19],
        ...,
        [ 0, 17, 16, ...,  1, 18, 19],
        [ 0, 17, 16, ...,  1, 18, 19],
        [ 0, 17, 16, ...,  1, 18

In [1]:
import yt 
from yt.data_objects.construction_data_containers import YTTiledArbitraryGrid
import matplotlib.pyplot as plt 
import numpy as np


ds = yt.load_sample("IsolatedGalaxy")
ds.index 
tag = YTTiledArbitraryGrid(ds.domain_left_edge,
                     ds.domain_right_edge,
                     (128,128,128), # global dimension
                     10, # nchunks = nprocs
                     ds=ds)

yt : [INFO     ] 2024-06-10 15:15:29,671 Sample dataset found in '/home/chavlin/hdd/data/yt_data/yt_sample_sets/IsolatedGalaxy/galaxy0030/galaxy0030'
yt : [INFO     ] 2024-06-10 15:15:29,846 Parameters: current_time              = 0.0060000200028298
yt : [INFO     ] 2024-06-10 15:15:29,847 Parameters: domain_dimensions         = [32 32 32]
yt : [INFO     ] 2024-06-10 15:15:29,847 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2024-06-10 15:15:29,848 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2024-06-10 15:15:29,849 Parameters: cosmological_simulation   = 0
Parsing Hierarchy : 100%|██████████████████| 173/173 [00:00<00:00, 23003.25it/s]
yt : [INFO     ] 2024-06-10 15:15:29,866 Gathering a field list (this may take a moment.)


In [2]:
tag.chunks

((128,), (64, 64), (25, 26, 25, 26, 26))

In [4]:
tag._grid_slc[0]

(slice(0, 128, None), slice(0, 64, None), slice(0, 25, None))

In [56]:
slc.start

0

In [5]:
tuple(tag.chunks[0])

(128,)

In [3]:
val = tag.to_dask(('enzo', 'Density'))

In [4]:
val

dask.array<setitem, shape=(128, 128, 128), dtype=float64, chunksize=(128, 64, 26), chunktype=numpy.ndarray>

In [7]:
np.sum(val.chunks[-1])

128