In [1]:
from spherical_voxels.intersections import SphericalVoxel, find_all_intersections
import numpy as np 

In [2]:
# create a single voxel
left_edge = np.array([0.4, np.pi/4, np.pi/4])
right_edge = np.array([0.6, np.pi/2, np.pi/2])
axis_id = {'r': 0, 'phi': 1, 'theta': 2}

vox = SphericalVoxel(left_edge, right_edge, axis_id)
left_edge, right_edge

(array([0.4       , 0.78539816, 0.78539816]),
 array([0.6       , 1.57079633, 1.57079633]))

In [3]:
vox.phi_plane_le

array([ 0.2, -0.2,  0. ,  0. ])

In [4]:
# find intersections 

v_model_vertex = np.array([0.6, np.pi/4, np.pi/4])
camer_pos_cartesian = np.array([0.01, -1, 0.01])
t_points, inters, inters_sp, inters_bools = find_all_intersections(v_model_vertex, camer_pos_cartesian, vox)

0.6
[0.3        0.3        0.42426407]


/home/chavlin/src/yt_general/yt_scratch/notebooks/yt_idv/spherical_voxels/intersections.py:114: RuntimeWarning: invalid value encountered in scalar divide
  phi = np.arctan(v[1] / v[0])
/home/chavlin/src/yt_general/yt_scratch/notebooks/yt_idv/spherical_voxels/intersections.py:116: RuntimeWarning: invalid value encountered in scalar divide
  theta = np.arctan(xy / v[2])


In [5]:
t_points

{'t_sphere_outer': array([-9.35927462e-01,  5.55111512e-17]),
 't_sphere_inner': array([-0.60576813, -0.33015933]),
 't_p_1': array([-0.]),
 't_p_2': array([-1.4429884]),
 't_cone_outer': array([-1.42856027,         inf]),
 't_cone_inner': array([inf, inf])}

In [6]:
inters

{'t_sphere_outer': [array([-0.18458108, -1.87226001, -0.26795845]),
  array([ 0.01, -1.  ,  0.01])],
 't_sphere_inner': [array([-0.11594033, -1.56456012, -0.16990536]),
  array([-0.05864074, -1.30769989, -0.08805308])],
 't_p_1': [array([ 0.01, -1.  ,  0.01])],
 't_p_2': [array([-0.29      , -2.34482759, -0.41854904])],
 't_cone_outer': [array([-0.28700037, -2.33138095, -0.41426407]),
  array([inf, inf, inf])],
 't_cone_inner': [array([inf, inf, inf]), array([inf, inf, inf])]}

In [7]:
inters_sp

{'t_sphere_outer': [array([ 1.90032351,  1.47252657, -1.42931807]),
  array([ 1.0001    , -1.56079666,  1.56079716])],
 't_sphere_inner': [array([ 1.57802356,  1.49682742, -1.46291748]),
  array([ 1.31197221,  1.52598369, -1.50363079])],
 't_p_1': [array([ 1.0001    , -1.56079666,  1.56079716])],
 't_p_2': [array([ 2.39947905,  1.44774471, -1.39546612])],
 't_cone_outer': [array([ 2.38522977,  1.44830942, -1.39623221]),
  array([inf, nan, nan])],
 't_cone_inner': [array([inf, nan, nan]), array([inf, nan, nan])]}

In [8]:
inters_bools

{'t_sphere_outer': [False, False],
 't_sphere_inner': [False, False],
 't_p_1': [False],
 't_p_2': [False],
 't_cone_outer': [False, False],
 't_cone_inner': [False, False]}

In [9]:
a = np.array([0.6300606 , 0.6300606 , 0.59414536])
np.sqrt(a[0]**2 + a[1]**2 + a[2]**2)

1.0709628509683469

In [10]:
inters_sp['t_p_2'][0] >= left_edge

array([ True,  True, False])

In [11]:
left_edge[1]

0.7853981633974483

In [12]:
inters_sp['t_p_2'][0][1]

1.4477447112461415